### ISSUE TITLE
SSO having issues with embedded resources

### ISSUE THREAD

**Issue by agrowe** [openequella/moodle-mod_openEQUELLA#32]
We have been receiving reports and I have experienced this as well, when resources are embedded in the page instead of open in new window, they sometimes do not show the resource and instead show the Equella login page.
I was able to make it show the screen this morning, but have been unable to get it to show again (logging out of Moodle / Equella etc and trying again).
Once they have opened a resource that uses Open in New Window, the embedded resources worked again.
This issue happened on Apple Safari browser on Windows 7, have not seen it using Firefox or heard of an issue before upgrading to 6.2QA1 and master branch a week ago.

**Comment by cathfitz** [comment]
This is an old issue and hasn't reappeared over last few year. Closing.
