### ISSUE TITLE
CSRF and sanitise vars in callbackmulti.php

### ISSUE THREAD

**Issue by danmarsden** [openequella/moodle-mod_openEQUELLA#41]
can sesskey checks be added to callbackmulti.php? - looks like it's called from within Moodle so should be possible?

also would be good to do some clean_param calls on the content that comes from the json_decode before passing them directly into the database.

**Comment by nelson-edalex** [comment]
Hi Dan,

We can't add sesskey to callbackmulti.php.  It's a callback PHP that EQUELLA uses to redirect user to after saving the selected resource in their course.

Cheers,
Nelson

**Comment by danmarsden** [comment]
but it happens within the user session right? - so you could add sesskey to the url you pass to equalla which is then passed back to Moodle?

if not - all good but it really needs some clean_param calls on that content before passing to the db...

**Comment by danmarsden** [comment]
I'm still not convinced.. but this probably wouldn't be a blocker on our end. having the clean_param stuff there makes it a lot cleaner than it was thanks.

**Comment by cathfitz** [comment]
Problem seems to have been adequately fixed.
