### ISSUE TITLE
Drag an drop. Item doesn't get contributed to equella with correct name and description 

### ISSUE THREAD

**Issue by mrblippy** [openequella/moodle-mod_openEQUELLA#46]
According to eqos-1611 if you drag and drop a file and choose the option 'Auto contribute file to Equella with metadata' option, the item that is contributed to equella should use the entered name and description (see screenshot)
![capture](https://user-images.githubusercontent.com/4625498/32922043-70adaada-cb84-11e7-907b-ab4f4bc83805.PNG)

Currently, the name and description that gets used for the item contributed to equella is the name of the file that is drag and dropped.
![capture](https://user-images.githubusercontent.com/4625498/32922181-21beaf18-cb85-11e7-91cd-4241a57059a2.PNG)

**Comment by abidingotter** [comment]
It would appear that those fields only get pushed into the XML, and you would need a custom script to extract them and save them in the appropriate fields.

**Comment by mrblippy** [comment]
Sounds like the test case was just wrong then

**Comment by abidingotter** [comment]
We *could* alter Equella to look at the collection item name and description paths and populate them (it really should anyway I would think)

**Comment by cathfitz** [comment]
Due to above change in oEQ this is now sorted.
