### ISSUE TITLE
Add support for the Moodle Privacy API

### ISSUE THREAD

**Issue by danmarsden** [openequella/moodle-mod_openEQUELLA#49]
Many organisations use continuous integration processes to run all tests prior to production deployment. This fails when Equella plugins are installed due to missing privacy api implementation.

it would be good if you could implement the privacy api in your plugins - more info:
https://docs.moodle.org/dev/Privacy_API

**Comment by danmarsden** [comment]
We have some clients planning to upgrade to 3.5 and this is currently blocking their ability to continue using the equalla plugin. It would be good to get this sorted asap if possible!

**Comment by exing1984** [comment]
Any update on this issue?

**Comment by cathfitz** [comment]
Implemented
