### ISSUE TITLE
Remove references to Pearson et. al. on GitHub Pages site

### ISSUE THREAD

**Issue by edalex-ian** [openequella/moodle-mod_openEQUELLA#54]
The GitHub Pages site for the moodle module needs the following paragraphs addressed:

> If you need to get the attention of the EQUELLA team send an email to support@equella.com.
> 
> Commercial support from EQUELLA Pearson regarding this integration requires a valid support contract.

Changes required:

* EQUELLA should be openEQUELLA
* If one needs to get attention, then they should use the methods mentioned in the 'Join the Community' section at https://equella.github.io/
* Possibly just remove the commercial support paragraph.

**Comment by cathfitz** [comment]
@edalex-ian please check to see if the github pages site is still working since the repo move.

**Comment by edalex-ian** [comment]
Addressed as part of #73
