### ISSUE TITLE
Implement release versioning

### ISSUE THREAD

**Issue by edalex-ian** [openequella/moodle-mod_openEQUELLA#55]
Currently users simply download the latest `master` archive (or clone) due to the lack of releases. Further, this also adds some difficulty in determining which version they're on.

As a result, let's create version 1.0 by:

* Specifying the version as part of the module (so that it's also displayed in Moodle);
* Creating a version 1.0 release on GitHub with associated release archive; and
* Documenting (possibly in CONTRIBUTING.md the process for creating future releases).

**Comment by DrCuriosity** [comment]
Yes please. The last marked release was in 2015; I think it is past time for another one.
