### ISSUE TITLE
'Equella Resource' should now be 'openEQUELLA Resource'

### ISSUE THREAD

**Issue by edalex-ian** [openequella/moodle-mod_openEQUELLA#57]

**Comment by edalex-ian** [comment]
It's been a long time, and we can't remember what this was specifically referencing. Closing for now, can revisit later if it comes up again.

**Comment by mrblippy** [comment]
Thin i found what @edalex-ian was referring to.  
![Capture](https://user-images.githubusercontent.com/4625498/76483346-ea64b180-646a-11ea-98e6-6d8b1bd44717.PNG)

**Comment by mrblippy** [comment]
That repository plugin appears to be in the core moodle code https://github.com/moodle/moodle/tree/master/repository/equella/lang/en

**Comment by edalex-ian** [comment]
Interesting. I guess we should probably raise a ticket against the Moodle repo.

I wonder if this is the same thing though, as it's only talking about 'repository' not 'resource'. And seeing I seemed to have used explicitly resource in the ticket title, I think that's something else.

That said though, what exactly is this functionality in the Moodle code base?

**Comment by cathfitz** [comment]
@mrblippy does this need action by you?
