### ISSUE TITLE
Simplify the layout of the openEQUELLA Resource settings page

### ISSUE THREAD

**Issue by mrblippy** [openequella/moodle-mod_openEQUELLA#59]
There are a number of ways we could simplify the setup of the openEQUELLA Resource activity module settings page, to make it more friendly to newcomers. This could include:

-  Disabling/enabling the equella_lti_oauth_key and equella_lti_oauth_secret fields based on the equella_enable_lti checkbox
-  Simplifying some of the long-winded help text, eg. Shared Secret, LTI settings

-  Adding /signon.do to the end of the text entered in the equella_url field, in case the user forgot to enter it themselves

- Changing the equella_action field to be a dropdown with two options, structured and selectOrAdd

- Making optional fields clearer to the user, so they know the bare minimum they need to do to get an openEQUELLA/moodle integration up and running (without having to read additional documentation)

**Comment by abidingotter** [comment]
"Changing the equella_action field to be a dropdown with two options, structured and selectOrAdd"

I think there are other options available?  I think "contribute" may be one of them, even if not mentioned in the Moodle UI.

**Comment by edalex-ian** [comment]
So all though this was marked in the 1.2 release, no code changes have been made for it, so I've removed the milestone.
