### ISSUE TITLE
Unable to install Moodle module for openEquella integration

### ISSUE THREAD

**Issue by abdkhanEummena** [openequella/moodle-mod_openEQUELLA#66]
I am trying to install Moodle module for the integration with openEquella. I followed the documentation but on opening the Moodle url **http://localhost:8099/**, I get a database error.

![image](https://user-images.githubusercontent.com/53985295/67024560-4c63f980-f10d-11e9-826e-6ff68c4c7705.png)

Docker logs for DB
![image](https://user-images.githubusercontent.com/53985295/67063661-39cedc00-f170-11e9-922a-c3d6f57486c3.png)

There is not much documentation about the same.
Any help would be highly appreciated.

I am running 
Ubuntu 16.04

**Comment by abdkhanEummena** [comment]
Any updates on this please.

**Comment by cathfitz** [comment]
@abdkhanEummena this is a moodle error not associated with oEQ integrations. Have you found a solution to this problem? Can this issue be closed?
