### ISSUE TITLE
openEquella resources set to display in new window produce a coding error when middle-/right-clicked to open in new tab/window

### ISSUE THREAD

**Issue by Novocastrian** [openequella/moodle-mod_openEQUELLA#71]
Hi there! 

The openEquella Resource in one of our older Moodle LMSs (3.1) has a default configuration to open openEquella resources in a new window. When you middle-click or right-click > open in new tab/window on the openEquella resource, it produces a coding error.

openEquella resource settings: 
![image](https://user-images.githubusercontent.com/4601813/74991306-b31d6900-5499-11ea-8dd7-8962a16ad58b.png)

**Expected behaviour (screenshot taken from a Moodle 3.5 instance):**
1. Set display settings of an equella resource to display in a new window.
2. Navigate to the openEquella resource in the course, then middle-click or right-click it > open in a new tab or window. 
3. Click on the link to the Equella resource:
![moodle 3 5 openequella in new tab result](https://user-images.githubusercontent.com/4601813/74993452-21185f00-549f-11ea-8e22-fd9652929b12.png)
_Note: the url of this page is the /mod/equella/view.php?id=somenumber page_

**Actual behaviour:**
1. Set display settings of an equella resource to display in a new window.
2. Navigate to the openEquella resource in the course, then middle-click or right-click it > open in a new tab or window. 
3. Moodle serves the mod/equella/view.php?id=somenumber page, but with this error instead:

> Coding error detected, it must be fixed by a programmer: check_browser_version is removed, please update your code to use core_useragent instead.
> 
> [More information about this error](https://docs.moodle.org/31/en/error/debug/codingerror)

![Coding error Higher Ed Moodle](https://user-images.githubusercontent.com/4601813/74993996-e6172b00-54a0-11ea-9335-ff3b3d7d3f8d.png)

**Troubleshooting notes**
Developer debugging in the problematic Moodle (3.1) did not produce anything that indicates the cause of this issue. The [More information about this error](https://docs.moodle.org/31/en/error/debug/codingerror) link suggested purging the site cache, but this did not resolve the issue either.

I am aware this is a _really old_ version of Moodle. However, upgrading the LMS is out-of-the-question at this point in time. Thus far, I'm unsuccessful in locating other reports of this issue online (particularly this GitHub project and [Moodle's English forums](https://moodle.org/course/view.php?id=5). Granted that people are inclined to open links in new tabs to maintain an easy reference to other resources in the course, is there a way to resolve this aside from telling people "don't middle-click or right-click Equella links as new tabs" or changing the display option?

**Comment by Novocastrian** [comment]
Bump. I know I am on a non-supported Moodle version (painfully aware, in fact), but is there a workaround for this issue that isn't 'upgrade moodle'?

**Comment by Novocastrian** [comment]
Bump. Sure is quiet here ...

**Comment by ChristianMurphy** [comment]
@Novocastrian for questions, the openEquella mailing lists are a good place to reach out https://github.com/openequella/openEQUELLA/blob/5aa5588eef073446e2c003db415248c237c64f0a/CONTRIBUTING.md#chatting

Also a friendly reminder that openEquella is an open source project, if people aren't haven't encountered this issue, you are welcome to research the issue and contribute an enhancement/fix.
