### ISSUE TITLE
Column UUID caused schema error on upgrade

### ISSUE THREAD

**Issue by yao9394** [openequella/moodle-mod_openEQUELLA#76]
**Describe the bug**
column uuid caused schema error

**To Reproduce**

1. for plugin users who installed this plugin before this version 2011072600
2. run `php admin/cli/check_database_schema.php`
3. Will see error of:

```
equella
 * column 'uuid' has incorrect type 'X', expected 'C'
```

**Expected behavior**

```
root@44bc1ff7eaf7:/siteroot# php admin/cli/check_database_schema.php
Database structure is ok.
```

**Stacktrace**

n/a

**Platform:**

- openEQUELLA Version: [e.g. 6.5, 6.6]
- Moodel Version: 35

**Comment by edalex-ian** [comment]
There's slight confusion on the related PR for this, so will pull this out of the 1.2 release for now. Can put it in to a future release once all in order.
