### ISSUE TITLE
Potentially remove grade, gradable functionality as grade items are not created anyway

### ISSUE THREAD

**Issue by troywilliams** [openequella/moodle-mod_openEQUELLA#79]
The plugin indicates that it supports grading and implements some of the required functionality but not all of it. This is also raised in issue #78 

Looking further into the plugin and its usage, I wonder if it should be implementing Moodle GradeAPI at all. https://docs.moodle.org/dev/Gradebook_API

The plugin is missing required equella_update_grades() function. So grade items are never built.
https://github.com/moodle/moodle/blob/master/lib/gradelib.php#L1378-L1409

This plugin IMO is more about linking to resources in Equella. The current plugin does not provide any method for assessing a student's interaction with an Equella resource or a way to grade that interaction.

I see there is some Equella LTI stuff in the https://github.com/openequella/moodle-mod_openEQUELLA/blob/master/locallib.php but I can't see how any grade data from Moodle could be sent back to Equella if no grade book items exist for Equella resource items.

Thoughts?

Kind regards,
Troy

**Comment by edalex-ian** [comment]
Hi Troy,

Yes, the focus of the plugin is definitely around the providing of content to Moodle from openEQUELLA - after all, oEQ is a content managements system. So as for the support of grading, I'm unclear as to who uses that or how much.

Where/what context are you using the module?

**Comment by troywilliams** [comment]
We work with a tertiary education provider in NZ that uses openEQUELLA as a CMS. We use the Moodle repository and activity module plugins to link resources from openEQUELLA and upload resources to openEQUELLA.

**Comment by edalex-ian** [comment]
Okay, excellent, so you use case is primarily content. Does having the grading code in the module cause you any specific issues then?

**Comment by troywilliams** [comment]
I can potentially work on a pull request to remove the grade functions?

**Comment by edalex-ian** [comment]
Definitely always welcome pull requests.

Plus, would definitely be interesting to see what this looks like. Just make sure you've also a contributor agreement with Apereo: https://www.apereo.org/licensing/agreements
