### ISSUE TITLE
I'm sorry for this,  but I couldn't find another way to ask for help

### ISSUE THREAD

**Issue by marcop69br** [openequella/moodle-mod_openEQUELLA#82]
I need a help to integrate moodle with openEquella with this plugin. 
 I'm looking for a freelancer to help me.
 my email : marco.borsoni@gmail.com

**Comment by edalex-ian** [comment]
Hello @marcop69br 

Depending on where you are in the world there are a number of support providers for openEQUELLA who could help. As the main developers of openEQUELLA and the Moodle Module, if you drop us a line at info@edalex.com we can point you in the right direction.

For general questions you may also want to try the openEQUELLA user mailing list: https://groups.google.com/a/apereo.org/forum/#!forum/equella-users

Good luck!
